apiVersion: apps/v1
kind: Deployment
metadata:
  name: hifive-app
  labels:
    app: hifive-app
spec:
  replicas: 2 # 서버 2대를 띄워서 안정성을 확보합니다.
  selector:
    matchLabels:
      app: hifive-app
  template:
    metadata:
      labels:
        app: hifive-app
    spec:
      containers:
      - name: hifive-app
        image: 601766312629.dkr.ecr.ap-northeast-2.amazonaws.com/hifive-web-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hifive-service
spec:
  type: LoadBalancer # 외부에서 접속 가능한 주소를 자동으로 생성합니다.
  selector:
    app: hifive-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80