name: Deploy to ECR

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 코드가 올라올 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hifive-web-app # 이전에 만든 ECR 리포지토리 이름
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # [중요] Deprecated된 set-output 대신 Environment Files 사용
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Update EKS Deployment
      run: |
        aws eks update-kubeconfig --region ap-northeast-2 --name hifive-lab-eks
        # 새 이미지로 Deployment 업데이트를 강제 실행합니다.
        kubectl set image deployment/hifive-app hifive-app=${{ steps.login-ecr.outputs.registry }}/hifive-web-app:latest
        kubectl rollout restart deployment/hifive-app